"""Hand-written knowledge that the automated pulls cannot reach.

Two holes in the fetched dataset are structural, not bugs to be fixed with a
better query:

**Wars.** Wikidata's P710 "participant" on a war points at the state that
actually fought, which for anything before about 1950 is a state that no
longer exists: World War II lists Nazi Germany, the Kingdom of Italy and the
Soviet Union, none of which carry an ISO code. So the pull came back with the
Iraq War as the most widely shared conflict in the world (39 countries) and
World War II with two, while the War of 1812 had the United States and nobody
to fight. The table below names the principal belligerents of the major wars
by the modern country that succeeded them.

**People.** Wikidata models a leader as a holder of an office, and the office
usually belongs to the historical state rather than the modern one. Muammar
Gaddafi ran Libya for 42 years and appeared nowhere on Libya's page, because
"Brotherly Leader" is an office of the Libyan Arab Jamahiriya. `FIGURES` names
the two or three people you would expect to see on each country's page.

Both are merged on top of the fetched data at load time, never written into
`countries.json`, so re-running the fetch scripts cannot wipe them.
"""
from .data_util import wiki_url


# --------------------------------------------------------------------------
# Wars, by the modern countries that fought them
# --------------------------------------------------------------------------
# name | start | end | ISO2 codes of the principal belligerents
WARS = [
    ("World War II", "1939", "1945",
     "DE IT JP RU US GB FR CN PL CA AU IN NZ ZA YU GR NL BE NO DK FI HU RO BG "
     "CZ AT PH KR MY MM ID EG LY TN DZ MA ET BR MX TR ES PT SE CH IE UA BY "
     "LT LV EE MD RS HR SI BA SK"),
    ("World War I", "1914", "1918",
     "DE AT FR GB RU IT US TR JP RO RS BE PT GR BG CA AU IN NZ ZA HU CZ PL "
     "UA SI HR BA SK ME LB SY IQ IL JO SA CN TH BR CU PA LR"),
    ("Napoleonic Wars", "1803", "1815",
     "FR GB RU AT DE ES PT IT NL SE DK PL BE CH EG NO"),
    ("Seven Years' War", "1756", "1763",
     "GB FR DE AT RU ES PT SE IN CA US"),
    ("Thirty Years' War", "1618", "1648",
     "DE CZ SE FR ES AT DK NL IT HU PL"),
    ("Hundred Years' War", "1337", "1453", "FR GB ES PT BE"),
    ("Crimean War", "1853", "1856", "RU GB FR TR IT"),
    ("Franco-Prussian War", "1870", "1871", "FR DE"),
    ("War of 1812", "1812", "1815", "US GB CA"),
    ("Mexican-American War", "1846", "1848", "US MX"),
    ("American Revolutionary War", "1775", "1783", "US GB FR ES NL"),
    ("American Civil War", "1861", "1865", "US"),
    ("Spanish-American War", "1898", "1898", "US ES CU PH PR"),
    ("Second Boer War", "1899", "1902", "GB ZA NL"),
    ("Russo-Japanese War", "1904", "1905", "RU JP KR CN"),
    ("Spanish Civil War", "1936", "1939", "ES DE IT RU PT MX"),
    ("Second Sino-Japanese War", "1937", "1945", "CN JP US RU"),
    ("Winter War", "1939", "1940", "FI RU SE"),
    ("Korean War", "1950", "1953",
     "KR KP US CN RU GB CA AU TR PH TH NZ ZA GR BE NL CO ET LU"),
    ("Suez Crisis", "1956", "1956", "EG GB FR IL"),
    ("Vietnam War", "1955", "1975", "VN US KR AU NZ TH PH LA KH CN RU"),
    ("Algerian War", "1954", "1962", "DZ FR"),
    ("Six-Day War", "1967", "1967", "IL EG SY JO IQ LB"),
    ("Yom Kippur War", "1973", "1973", "IL EG SY IQ JO SA MA CU"),
    ("Soviet-Afghan War", "1979", "1989", "AF RU PK US"),
    ("Iran-Iraq War", "1980", "1988", "IR IQ KW SA"),
    ("Falklands War", "1982", "1982", "GB AR"),
    ("Gulf War", "1990", "1991",
     "IQ KW US SA GB FR EG SY AE QA OM BH CA AU IT"),
    ("Yugoslav Wars", "1991", "2001", "RS HR BA SI ME MK XK AL"),
    ("Rwandan genocide", "1994", "1994", "RW UG CD BI FR"),
    ("Kosovo War", "1998", "1999", "RS XK AL US GB FR DE IT"),
    ("Second Congo War", "1998", "2003",
     "CD RW UG AO ZW NA BI TD SD LY"),
    ("War in Afghanistan (2001-2021)", "2001", "2021",
     "AF US GB CA DE IT FR AU NL PL TR ES DK NO RO GE PK"),
    ("Iraq War", "2003", "2011", "IQ US GB AU PL ES IT KR DK"),
    ("First Libyan Civil War", "2011", "2011", "LY FR GB US IT QA AE CA"),
    ("Syrian civil war", "2011", "2024", "SY RU IR TR US SA QA IQ LB IL"),
    ("Russian invasion of Ukraine", "2022", None, "UA RU BY"),
    ("Indo-Pakistani wars and conflicts", "1947", None, "IN PK BD CN"),
    ("Chinese Civil War", "1927", "1949", "CN RU US"),
    ("Greek War of Independence", "1821", "1829", "GR TR RU GB FR EG"),
    ("Balkan Wars", "1912", "1913", "GR BG RS ME TR AL MK RO"),
    ("Paraguayan War", "1864", "1870", "PY BR AR UY"),
    ("War of the Pacific", "1879", "1884", "CL PE BO"),
    ("Chaco War", "1932", "1935", "PY BO"),
    ("Nigerian Civil War", "1967", "1970", "NG"),
    ("Eritrean War of Independence", "1961", "1991", "ER ET"),
    ("Angolan Civil War", "1975", "2002", "AO CU ZA RU NA CD"),
    ("Mozambican Civil War", "1977", "1992", "MZ ZW ZA"),
    ("Cambodian-Vietnamese War", "1978", "1989", "KH VN TH CN"),
    ("Sri Lankan Civil War", "1983", "2009", "LK IN"),
    ("Bangladesh Liberation War", "1971", "1971", "BD PK IN"),
    ("Gran Colombia-Peru War", "1828", "1829", "CO PE EC VE"),
]


# --------------------------------------------------------------------------
# The people you would expect to find on a country's page
# --------------------------------------------------------------------------
# "Name|what they are known for". The Wikipedia link is derived from the name.
FIGURES = {
    "AD": ["Boris Skossyreff|Adventurer who declared himself king in 1934"],
    "AE": ["Zayed bin Sultan Al Nahyan|Founding president, 1971-2004",
           "Mohammed bin Rashid Al Maktoum|Ruler of Dubai"],
    "AF": ["Ahmad Shah Durrani|Founder of the Afghan state, 1747",
           "Ahmad Shah Massoud|Resistance commander, the Lion of Panjshir",
           "Mohammed Zahir Shah|Last king, reigned 1933-1973"],
    "AG": ["Vere Bird|First prime minister after independence",
           "Viv Richards|Cricketer"],
    "AL": ["Skanderbeg|National hero who resisted the Ottomans",
           "Enver Hoxha|Communist dictator, 1944-1985",
           "Ismail Kadare|Novelist"],
    "AM": ["Tigranes the Great|King of Armenia at its greatest extent",
           "Gregory the Illuminator|Converted Armenia to Christianity in 301",
           "Aram Khachaturian|Composer"],
    "AO": ["Agostinho Neto|First president and independence leader",
           "Jonas Savimbi|UNITA rebel leader in the civil war"],
    "AR": ["Juan Peron|President and founder of Peronism",
           "Eva Peron|First lady and political figure",
           "Jose de San Martin|Liberator of Argentina, Chile and Peru",
           "Diego Maradona|Footballer"],
    "AT": ["Maria Theresa|Habsburg ruler, 1740-1780",
           "Wolfgang Amadeus Mozart|Composer",
           "Sigmund Freud|Founder of psychoanalysis"],
    "AU": ["Edmund Barton|First prime minister, 1901",
           "Ned Kelly|Bushranger and folk figure",
           "Gough Whitlam|Prime minister dismissed in 1975"],
    "AZ": ["Heydar Aliyev|President, 1993-2003",
           "Nizami Ganjavi|Medieval poet"],
    "BA": ["Alija Izetbegovic|First president of independent Bosnia",
           "Ivo Andric|Nobel laureate novelist"],
    "BB": ["Errol Barrow|Father of independence",
           "Rihanna|Singer"],
    "BD": ["Sheikh Mujibur Rahman|Founding leader of Bangladesh",
           "Muhammad Yunus|Nobel laureate, microfinance pioneer",
           "Sheikh Hasina|Prime minister, ousted in 2024"],
    "BE": ["Leopold II|King whose Congo Free State killed millions",
           "Rene Magritte|Surrealist painter",
           "Georges Simenon|Novelist"],
    "BF": ["Thomas Sankara|Revolutionary president, 1983-1987",
           "Blaise Compaore|President, 1987-2014"],
    "BG": ["Simeon I|Tsar of the First Bulgarian Empire",
           "Vasil Levski|Revolutionary against Ottoman rule",
           "Todor Zhivkov|Communist leader, 1954-1989"],
    "BH": ["Isa bin Salman Al Khalifa|Emir who led Bahrain to independence"],
    "BI": ["Melchior Ndadaye|First elected Hutu president, killed in 1993",
           "Pierre Nkurunziza|President, 2005-2020"],
    "BJ": ["Behanzin|Last independent king of Dahomey",
           "Mathieu Kerekou|Marxist ruler, then elected president"],
    "BN": ["Hassanal Bolkiah|Sultan since 1967"],
    "BO": ["Simon Bolivar|Liberator the country is named for",
           "Evo Morales|First indigenous president",
           "Tupac Katari|Leader of the 1781 indigenous rebellion"],
    "BR": ["Pedro II|Last emperor of Brazil",
           "Getulio Vargas|President and dictator",
           "Pele|Footballer",
           "Oscar Niemeyer|Architect of Brasilia"],
    "BS": ["Lynden Pindling|Father of the nation",
           "Sidney Poitier|Actor"],
    "BT": ["Jigme Singye Wangchuck|King who coined Gross National Happiness",
           "Ngawang Namgyal|Unifier of Bhutan in the 17th century"],
    "BW": ["Seretse Khama|First president",
           "Ian Khama|President, 2008-2018"],
    "BY": ["Alexander Lukashenko|President since 1994",
           "Svetlana Alexievich|Nobel laureate writer"],
    "BZ": ["George Cadle Price|Father of independence"],
    "CA": ["John A. Macdonald|First prime minister",
           "Pierre Trudeau|Prime minister, 1968-1984",
           "Terry Fox|Runner and cancer-research campaigner"],
    "CD": ["Patrice Lumumba|First prime minister, assassinated in 1961",
           "Mobutu Sese Seko|Dictator, 1965-1997",
           "Denis Mukwege|Nobel laureate surgeon"],
    "CF": ["Jean-Bedel Bokassa|Self-crowned emperor, 1976-1979",
           "Barthelemy Boganda|Independence leader"],
    "CG": ["Denis Sassou Nguesso|President for most of the past 45 years"],
    "CH": ["William Tell|Founding legend of the confederation",
           "Henri Dunant|Founder of the Red Cross",
           "Le Corbusier|Architect"],
    "CI": ["Felix Houphouet-Boigny|First president, 1960-1993",
           "Didier Drogba|Footballer and peace broker"],
    "CL": ["Bernardo O'Higgins|Independence leader",
           "Salvador Allende|President overthrown in 1973",
           "Augusto Pinochet|Dictator, 1973-1990",
           "Pablo Neruda|Nobel laureate poet"],
    "CM": ["Ahmadou Ahidjo|First president",
           "Paul Biya|President since 1982",
           "Roger Milla|Footballer"],
    "CN": ["Mao Zedong|Founder of the People's Republic",
           "Deng Xiaoping|Architect of the economic opening",
           "Confucius|Philosopher",
           "Qin Shi Huang|First emperor of a unified China"],
    "CO": ["Simon Bolivar|Liberator",
           "Gabriel Garcia Marquez|Nobel laureate novelist",
           "Pablo Escobar|Drug lord"],
    "CR": ["Jose Figueres Ferrer|Abolished the army in 1948",
           "Oscar Arias|Nobel Peace Prize for the Central America accords"],
    "CU": ["Fidel Castro|Revolutionary leader, 1959-2008",
           "Che Guevara|Revolutionary",
           "Jose Marti|Poet and independence hero"],
    "CV": ["Amilcar Cabral|Independence leader",
           "Cesaria Evora|Singer"],
    "CY": ["Makarios III|Archbishop and first president",
           "Zeno of Citium|Founder of Stoicism"],
    "CZ": ["Vaclav Havel|Playwright and first post-communist president",
           "Charles IV|Holy Roman Emperor who built Prague",
           "Jan Hus|Reformer burned at the stake in 1415",
           "Antonin Dvorak|Composer"],
    "DE": ["Otto von Bismarck|Unified Germany in 1871",
           "Adolf Hitler|Nazi dictator, 1933-1945",
           "Konrad Adenauer|First chancellor of West Germany",
           "Angela Merkel|Chancellor, 2005-2021"],
    "DJ": ["Hassan Gouled Aptidon|First president"],
    "DK": ["Harald Bluetooth|Viking king who Christianised Denmark",
           "Hans Christian Andersen|Writer of fairy tales",
           "Niels Bohr|Physicist"],
    "DM": ["Eugenia Charles|Caribbean's first female prime minister"],
    "DO": ["Juan Pablo Duarte|Founding father",
           "Rafael Trujillo|Dictator, 1930-1961"],
    "DZ": ["Abdelaziz Bouteflika|President, 1999-2019",
           "Emir Abdelkader|Leader of resistance to the French conquest",
           "Houari Boumediene|President, 1965-1978"],
    "EC": ["Eloy Alfaro|Liberal revolutionary president",
           "Rafael Correa|President, 2007-2017"],
    "EE": ["Lennart Meri|First president after independence",
           "Arvo Part|Composer"],
    "EG": ["Gamal Abdel Nasser|President who nationalised the Suez Canal",
           "Anwar Sadat|President who made peace with Israel",
           "Cleopatra|Last pharaoh of Egypt",
           "Naguib Mahfouz|Nobel laureate novelist"],
    "ER": ["Isaias Afwerki|President since independence in 1993"],
    "ES": ["Francisco Franco|Dictator, 1939-1975",
           "Isabella I of Castile|Queen who financed Columbus",
           "Pablo Picasso|Painter",
           "Miguel de Cervantes|Author of Don Quixote"],
    "ET": ["Haile Selassie|Emperor, 1930-1974",
           "Menelik II|Defeated Italy at Adwa in 1896",
           "Abiy Ahmed|Prime minister and Nobel laureate"],
    "FI": ["Carl Gustaf Emil Mannerheim|Marshal and president",
           "Jean Sibelius|Composer",
           "Tarja Halonen|First female president"],
    "FJ": ["Ratu Sir Lala Sukuna|Statesman and nation-builder"],
    "FM": ["Tosiwo Nakayama|First president"],
    "FR": ["Napoleon|Emperor, 1804-1815",
           "Charles de Gaulle|Wartime leader and president",
           "Joan of Arc|Saint and military leader",
           "Marie Curie|Twice a Nobel laureate"],
    "GA": ["Omar Bongo|President, 1967-2009"],
    "GB": ["Winston Churchill|Wartime prime minister",
           "Elizabeth II|Queen, 1952-2022",
           "William Shakespeare|Playwright",
           "Isaac Newton|Physicist and mathematician"],
    "GD": ["Maurice Bishop|Revolutionary prime minister, killed in 1983"],
    "GE": ["David IV|King of Georgia's golden age",
           "Eduard Shevardnadze|Soviet foreign minister, then president",
           "Joseph Stalin|Soviet leader, born in Gori"],
    "GH": ["Kwame Nkrumah|First president and pan-Africanist",
           "Kofi Annan|UN Secretary-General",
           "Jerry Rawlings|Military ruler, then elected president"],
    "GM": ["Dawda Jawara|First president",
           "Yahya Jammeh|Ruler, 1994-2017"],
    "GN": ["Ahmed Sekou Toure|First president, refused French terms in 1958"],
    "GQ": ["Teodoro Obiang Nguema Mbasogo|President since 1979"],
    "GR": ["Alexander the Great|Macedonian conqueror",
           "Pericles|Statesman of Athens",
           "Eleftherios Venizelos|Modern Greece's dominant statesman",
           "Aristotle|Philosopher"],
    "GT": ["Jacobo Arbenz|President overthrown in a 1954 coup",
           "Rigoberta Menchu|Nobel laureate indigenous rights campaigner",
           "Efrain Rios Montt|Dictator convicted of genocide"],
    "GW": ["Amilcar Cabral|Independence leader, assassinated in 1973"],
    "GY": ["Cheddi Jagan|Independence-era leader and president",
           "Forbes Burnham|First prime minister of independent Guyana"],
    "HN": ["Francisco Morazan|Leader of the Central American federation",
           "Manuel Zelaya|President removed in the 2009 coup"],
    "HR": ["Franjo Tudjman|First president of independent Croatia",
           "Josip Broz Tito|Yugoslav leader, born in Croatia",
           "Nikola Tesla|Inventor, born in Croatia"],
    "HT": ["Toussaint Louverture|Leader of the Haitian Revolution",
           "Jean-Jacques Dessalines|Declared independence in 1804",
           "Francois Duvalier|Dictator known as Papa Doc"],
    "HU": ["Stephen I of Hungary|Founding king",
           "Lajos Kossuth|Leader of the 1848 revolution",
           "Imre Nagy|Prime minister executed after 1956"],
    "ID": ["Sukarno|Founding president",
           "Suharto|Ruler, 1967-1998",
           "Raden Adjeng Kartini|Pioneer of women's education"],
    "IE": ["Michael Collins|Revolutionary leader",
           "Eamon de Valera|Taoiseach and president",
           "James Joyce|Novelist",
           "Mary Robinson|First female president"],
    "IL": ["David Ben-Gurion|Founding prime minister",
           "Golda Meir|Prime minister, 1969-1974",
           "Yitzhak Rabin|Prime minister assassinated in 1995"],
    "IN": ["Mahatma Gandhi|Led the independence movement",
           "Jawaharlal Nehru|First prime minister",
           "B. R. Ambedkar|Architect of the constitution",
           "Indira Gandhi|Prime minister, assassinated in 1984",
           "Narendra Modi|Prime minister since 2014"],
    "IQ": ["Saddam Hussein|Ruler, 1979-2003",
           "Hammurabi|Babylonian king and lawgiver",
           "Faisal I of Iraq|First king of modern Iraq"],
    "IR": ["Ruhollah Khomeini|Leader of the 1979 revolution",
           "Mohammad Reza Pahlavi|Last Shah of Iran",
           "Cyrus the Great|Founder of the Persian Empire",
           "Mohammad Mosaddegh|Prime minister overthrown in 1953"],
    "IS": ["Jon Sigurdsson|Leader of the independence movement",
           "Halldor Laxness|Nobel laureate novelist",
           "Vigdis Finnbogadottir|World's first elected female head of state"],
    "IT": ["Giuseppe Garibaldi|Unifier of Italy",
           "Benito Mussolini|Fascist dictator, 1922-1943",
           "Leonardo da Vinci|Polymath",
           "Julius Caesar|Roman general and dictator"],
    "JM": ["Marcus Garvey|Pan-Africanist leader",
           "Bob Marley|Musician",
           "Usain Bolt|Sprinter"],
    "JO": ["Hussein of Jordan|King, 1952-1999",
           "Abdullah I of Jordan|Founding king"],
    "JP": ["Emperor Meiji|Presided over Japan's modernisation",
           "Hirohito|Emperor through the war years",
           "Tokugawa Ieyasu|Founder of the shogunate",
           "Shinzo Abe|Longest-serving prime minister"],
    "KE": ["Jomo Kenyatta|Founding president",
           "Wangari Maathai|Nobel laureate environmentalist",
           "Daniel arap Moi|President, 1978-2002"],
    "KG": ["Askar Akayev|First president",
           "Manas|Hero of the national epic"],
    "KH": ["Norodom Sihanouk|King and head of state for most of 60 years",
           "Pol Pot|Khmer Rouge leader",
           "Jayavarman VII|King who built the Angkor temples"],
    "KI": ["Ieremia Tabai|First president"],
    "KM": ["Ahmed Abdallah|Independence-era president"],
    "KN": ["Robert Bradshaw|First premier",
           "Alexander Hamilton|US founding father, born in Nevis"],
    "KP": ["Kim Il-sung|Founding leader",
           "Kim Jong-il|Leader, 1994-2011",
           "Kim Jong-un|Leader since 2011"],
    "KR": ["Park Chung-hee|President who drove industrialisation",
           "Kim Dae-jung|Nobel laureate president",
           "Sejong the Great|King who created the Korean alphabet"],
    "KW": ["Jaber Al-Ahmad Al-Sabah|Emir through the Iraqi invasion"],
    "KZ": ["Nursultan Nazarbayev|President, 1991-2019",
           "Abai Qunanbaiuly|National poet"],
    "LA": ["Kaysone Phomvihane|Communist leader who founded the republic",
           "Souphanouvong|The Red Prince"],
    "LB": ["Rafic Hariri|Prime minister assassinated in 2005",
           "Kahlil Gibran|Poet",
           "Bachir Gemayel|President-elect killed in 1982"],
    "LC": ["Derek Walcott|Nobel laureate poet",
           "Arthur Lewis|Nobel laureate economist"],
    "LI": ["Franz Joseph II|Prince who moved the court to Vaduz"],
    "LK": ["Sirimavo Bandaranaike|World's first female prime minister",
           "Ashoka|Emperor who brought Buddhism to the island",
           "D. S. Senanayake|First prime minister"],
    "LR": ["William Tubman|President, 1944-1971",
           "Ellen Johnson Sirleaf|Africa's first elected female head of state",
           "Charles Taylor|Warlord and president convicted of war crimes"],
    "LS": ["Moshoeshoe I|Founder of the Basotho nation"],
    "LT": ["Vytautas the Great|Grand Duke at Lithuania's greatest extent",
           "Vytautas Landsbergis|Led the break from the Soviet Union"],
    "LU": ["Jean of Luxembourg|Grand Duke, 1964-2000",
           "Robert Schuman|Architect of European integration"],
    "LV": ["Karlis Ulmanis|Interwar leader",
           "Vaira Vike-Freiberga|President, 1999-2007"],
    "LY": ["Muammar Gaddafi|Ruler, 1969-2011",
           "Omar Mukhtar|Leader of resistance to Italian rule",
           "Idris of Libya|The country's only king"],
    "MA": ["Hassan II|King, 1961-1999",
           "Mohammed V|Led Morocco to independence",
           "Ibn Battuta|Medieval traveller"],
    "MC": ["Rainier III|Prince, 1949-2005",
           "Grace Kelly|Actress and Princess of Monaco"],
    "MD": ["Stephen the Great|Medieval ruler of Moldavia",
           "Maia Sandu|President since 2020"],
    "ME": ["Petar II Petrovic-Njegos|Prince-bishop and poet",
           "Milo Djukanovic|Dominant politician since 1991"],
    "MG": ["Andrianampoinimerina|King who unified the highlands",
           "Didier Ratsiraka|President for two long spells"],
    "MH": ["Amata Kabua|First president"],
    "MK": ["Alexander the Great|Ancient Macedonian conqueror",
           "Mother Teresa|Nobel laureate, born in Skopje",
           "Kiro Gligorov|First president"],
    "ML": ["Mansa Musa|Emperor of Mali, the richest man in history",
           "Sundiata Keita|Founder of the Mali Empire",
           "Modibo Keita|First president"],
    "MM": ["Aung San|Independence leader",
           "Aung San Suu Kyi|Nobel laureate and civilian leader",
           "Ne Win|Military ruler, 1962-1988"],
    "MN": ["Genghis Khan|Founder of the Mongol Empire",
           "Kublai Khan|Emperor of the Yuan dynasty",
           "Damdin Sukhbaatar|Revolutionary hero"],
    "MR": ["Moktar Ould Daddah|First president"],
    "MT": ["Dom Mintoff|Prime minister who ended the British base",
           "Jean Parisot de Valette|Grand Master who held the 1565 siege"],
    "MU": ["Seewoosagur Ramgoolam|Father of the nation"],
    "MV": ["Maumoon Abdul Gayoom|President, 1978-2008",
           "Mohamed Nasheed|First democratically elected president"],
    "MW": ["Hastings Banda|President for life, 1966-1994"],
    "MX": ["Benito Juarez|Reformist president",
           "Emiliano Zapata|Revolutionary leader",
           "Frida Kahlo|Painter",
           "Lazaro Cardenas|President who nationalised the oil"],
    "MY": ["Tunku Abdul Rahman|First prime minister",
           "Mahathir Mohamad|Prime minister for 24 years"],
    "MZ": ["Samora Machel|First president",
           "Eduardo Mondlane|Founder of the liberation movement",
           "Graca Machel|Stateswoman"],
    "NA": ["Sam Nujoma|Founding president",
           "Hendrik Witbooi|Leader of resistance to German rule"],
    "NE": ["Hamani Diori|First president"],
    "NG": ["Nnamdi Azikiwe|First president",
           "Chinua Achebe|Novelist",
           "Wole Soyinka|Nobel laureate playwright",
           "Obafemi Awolowo|Statesman"],
    "NI": ["Augusto Cesar Sandino|Guerrilla leader the Sandinistas are named for",
           "Daniel Ortega|Revolutionary and long-serving president",
           "Ruben Dario|Poet"],
    "NL": ["William the Silent|Leader of the revolt against Spain",
           "Rembrandt|Painter",
           "Anne Frank|Diarist",
           "Vincent van Gogh|Painter"],
    "NO": ["Harald Fairhair|First king of a united Norway",
           "Fridtjof Nansen|Explorer and Nobel laureate",
           "Henrik Ibsen|Playwright",
           "Roald Amundsen|First to the South Pole"],
    "NP": ["Prithvi Narayan Shah|Unifier of Nepal",
           "Tenzing Norgay|First to summit Everest, with Hillary",
           "Gautama Buddha|Born at Lumbini"],
    "NR": ["Hammer DeRoburt|Founding president"],
    "NZ": ["Michael Joseph Savage|Built the welfare state",
           "Edmund Hillary|First to summit Everest",
           "Kate Sheppard|Won women the vote in 1893",
           "Jacinda Ardern|Prime minister, 2017-2023"],
    "OM": ["Qaboos bin Said|Sultan, 1970-2020"],
    "PA": ["Omar Torrijos|Won back the Canal Zone",
           "Manuel Noriega|Dictator removed by the 1989 invasion"],
    "PE": ["Tupac Amaru II|Leader of the great indigenous revolt",
           "Pachacuti|Inca emperor who built Machu Picchu",
           "Mario Vargas Llosa|Nobel laureate novelist"],
    "PG": ["Michael Somare|Founding prime minister"],
    "PH": ["Jose Rizal|National hero and writer",
           "Ferdinand Marcos|Dictator, 1965-1986",
           "Corazon Aquino|President of the People Power revolution"],
    "PK": ["Muhammad Ali Jinnah|Founder of Pakistan",
           "Benazir Bhutto|Prime minister, assassinated in 2007",
           "Malala Yousafzai|Nobel laureate education campaigner",
           "Abdul Sattar Edhi|Philanthropist"],
    "PL": ["Lech Walesa|Solidarity leader and president",
           "John Paul II|Pope, born in Wadowice",
           "Nicolaus Copernicus|Astronomer",
           "Jozef Pilsudski|Founder of the interwar republic"],
    "PS": ["Yasser Arafat|PLO leader and president",
           "Mahmoud Darwish|National poet",
           "Edward Said|Scholar"],
    "PT": ["Vasco da Gama|Sailed to India",
           "Henry the Navigator|Patron of the age of discovery",
           "Antonio de Oliveira Salazar|Dictator, 1932-1968",
           "Fernando Pessoa|Poet"],
    "PW": ["Haruo Remeliik|First president"],
    "PY": ["Jose Gaspar Rodriguez de Francia|First dictator",
           "Alfredo Stroessner|Dictator, 1954-1989"],
    "QA": ["Hamad bin Khalifa Al Thani|Emir who founded Al Jazeera"],
    "RO": ["Nicolae Ceausescu|Communist dictator executed in 1989",
           "Vlad the Impaler|Prince of Wallachia",
           "Michael the Brave|First to unite the Romanian principalities"],
    "RS": ["Josip Broz Tito|Yugoslav leader, 1945-1980",
           "Slobodan Milosevic|President tried for war crimes",
           "Nikola Tesla|Inventor",
           "Karadorde|Leader of the first Serbian uprising"],
    "RU": ["Peter the Great|Tsar who westernised Russia",
           "Vladimir Lenin|Leader of the October Revolution",
           "Joseph Stalin|Soviet leader, 1924-1953",
           "Catherine the Great|Empress, 1762-1796",
           "Mikhail Gorbachev|Last Soviet leader"],
    "RW": ["Paul Kagame|President since 2000",
           "Juvenal Habyarimana|President whose death triggered the genocide"],
    "SA": ["Ibn Saud|Founder of the kingdom",
           "Faisal of Saudi Arabia|King who led the 1973 oil embargo",
           "Mohammed bin Salman|Crown prince"],
    "SB": ["Peter Kenilorea|First prime minister"],
    "SC": ["France-Albert Rene|President, 1977-2004"],
    "SD": ["Muhammad Ahmad|The Mahdi, who took Khartoum in 1885",
           "Omar al-Bashir|Ruler, 1989-2019, indicted for Darfur"],
    "SE": ["Gustavus Adolphus|Warrior king of the Thirty Years' War",
           "Alfred Nobel|Inventor of dynamite, founder of the prizes",
           "Olof Palme|Prime minister assassinated in 1986",
           "Greta Thunberg|Climate campaigner"],
    "SG": ["Lee Kuan Yew|Founding prime minister",
           "Stamford Raffles|Founder of the colonial port"],
    "SI": ["France Preseren|National poet",
           "Milan Kucan|First president"],
    "SK": ["Alexander Dubcek|Leader of the Prague Spring",
           "Milan Rastislav Stefanik|Co-founder of Czechoslovakia"],
    "SL": ["Siaka Stevens|President, 1971-1985",
           "Ahmad Tejan Kabbah|President who ended the civil war"],
    "SM": ["Saint Marinus|Founder of the republic in 301"],
    "SN": ["Leopold Sedar Senghor|Poet and founding president",
           "Cheikh Anta Diop|Historian",
           "Youssou N'Dour|Musician"],
    "SO": ["Mohamed Siad Barre|Ruler, 1969-1991",
           "Sayyid Mohammed Abdullah Hassan|Anti-colonial leader"],
    "SR": ["Johan Ferrier|First president",
           "Desi Bouterse|Coup leader and later president"],
    "SS": ["John Garang|Leader of the southern rebellion",
           "Salva Kiir Mayardit|First president"],
    "ST": ["Manuel Pinto da Costa|First president"],
    "SV": ["Oscar Romero|Archbishop assassinated in 1980",
           "Farabundo Marti|Communist leader of the 1932 uprising"],
    "SY": ["Hafez al-Assad|President, 1971-2000",
           "Bashar al-Assad|President, 2000-2024",
           "Saladin|Sultan who retook Jerusalem, buried in Damascus"],
    "SZ": ["Sobhuza II|King for 82 years, the longest verified reign",
           "Mswati III|King since 1986"],
    "TD": ["Idriss Deby|President, 1990-2021",
           "Hissene Habre|Dictator convicted of crimes against humanity"],
    "TG": ["Gnassingbe Eyadema|President, 1967-2005"],
    "TH": ["Bhumibol Adulyadej|King, 1946-2016",
           "Chulalongkorn|King who kept Siam independent",
           "Thaksin Shinawatra|Prime minister ousted in 2006"],
    "TJ": ["Emomali Rahmon|President since 1992",
           "Ismoil Somoni|Founder of the Samanid state"],
    "TL": ["Xanana Gusmao|Resistance leader and first president",
           "Jose Ramos-Horta|Nobel laureate and president"],
    "TM": ["Saparmurat Niyazov|President for life, 1991-2006"],
    "TN": ["Habib Bourguiba|Founding president",
           "Zine El Abidine Ben Ali|President ousted in 2011",
           "Mohamed Bouazizi|Street vendor whose death began the Arab Spring"],
    "TO": ["Taufa'ahau Tupou IV|King, 1965-2006"],
    "TR": ["Mustafa Kemal Ataturk|Founder of the republic",
           "Suleiman the Magnificent|Ottoman sultan at the empire's height",
           "Mehmed II|Conqueror of Constantinople",
           "Orhan Pamuk|Nobel laureate novelist"],
    "TT": ["Eric Williams|First prime minister and historian",
           "V. S. Naipaul|Nobel laureate novelist"],
    "TV": ["Toaripi Lauti|First prime minister"],
    "TW": ["Chiang Kai-shek|Nationalist leader who retreated to Taiwan",
           "Lee Teng-hui|First directly elected president",
           "Tsai Ing-wen|President, 2016-2024"],
    "TZ": ["Julius Nyerere|Founding president",
           "Abeid Karume|First president of Zanzibar"],
    "UA": ["Bohdan Khmelnytsky|Cossack hetman",
           "Taras Shevchenko|National poet",
           "Volodymyr Zelenskyy|Wartime president"],
    "UG": ["Idi Amin|Dictator, 1971-1979",
           "Yoweri Museveni|President since 1986",
           "Milton Obote|Prime minister and president"],
    "US": ["George Washington|First president",
           "Abraham Lincoln|President through the Civil War",
           "Martin Luther King Jr.|Civil rights leader",
           "Franklin D. Roosevelt|President, 1933-1945"],
    "UY": ["Jose Gervasio Artigas|Father of Uruguayan independence",
           "Jose Mujica|President known for his austerity"],
    "UZ": ["Timur|Conqueror who built his capital at Samarkand",
           "Islam Karimov|President, 1991-2016",
           "Ulugh Beg|Astronomer and ruler"],
    "VA": ["John Paul II|Pope, 1978-2005",
           "Francis|Pope, 2013-2025",
           "Michelangelo|Painter of the Sistine Chapel"],
    "VC": ["Milton Cato|First prime minister"],
    "VE": ["Simon Bolivar|Liberator of northern South America",
           "Hugo Chavez|President, 1999-2013",
           "Francisco de Miranda|Precursor of independence"],
    "VN": ["Ho Chi Minh|Founding leader",
           "Vo Nguyen Giap|General who won at Dien Bien Phu",
           "Trung Sisters|Led the revolt against Han rule"],
    "VU": ["Walter Lini|Founding prime minister"],
    "WS": ["Malietoa Tanumafili II|Head of state, 1962-2007"],
    "XK": ["Ibrahim Rugova|First president",
           "Adem Jashari|Founder of the Kosovo Liberation Army"],
    "YE": ["Ali Abdullah Saleh|President, 1978-2012",
           "Queen of Sheba|Ruler of the ancient Sabaean kingdom"],
    "ZA": ["Nelson Mandela|First president of a democratic South Africa",
           "Desmond Tutu|Archbishop and Nobel laureate",
           "Shaka|King who forged the Zulu kingdom",
           "F. W. de Klerk|President who ended apartheid"],
    "ZM": ["Kenneth Kaunda|Founding president"],
    "ZW": ["Robert Mugabe|Ruler, 1980-2017",
           "Joshua Nkomo|Liberation leader"],
}


def _people_for(iso):
    out = []
    for entry in FIGURES.get(iso, []):
        name, _, note = entry.partition("|")
        out.append({"name": name, "note": note or None,
                    "wiki": wiki_url(name), "source": "curated"})
    return out


def apply(countries):
    """Merge the curated tables into the loaded dataset, in place."""
    # Wars keep whatever QID the fetched data already used for the same war,
    # so a curated participant lands on the same topic page as a fetched one
    # instead of creating a second node under a slug.
    qid_by_name = {}
    for c in countries.values():
        for w in c.get("wars") or []:
            if w.get("name") and w.get("qid"):
                qid_by_name.setdefault(w["name"].lower(), w["qid"])

    for name, start, end, isos in WARS:
        qid = qid_by_name.get(name.lower())
        for iso in isos.split():
            c = countries.get(iso)
            if not c:
                continue
            wars = c.setdefault("wars", [])
            if any((w.get("name") or "").lower() == name.lower() for w in wars):
                continue
            wars.append({"name": name, "qid": qid, "wiki": wiki_url(name),
                         "start": start, "end": end, "fame": 400,
                         "source": "curated"})

    # Biggest conflicts first, so a fact card shows the wars people have heard
    # of rather than three border skirmishes.
    for c in countries.values():
        if c.get("wars"):
            c["wars"].sort(key=lambda w: -(w.get("fame") or 0))

    for iso, c in countries.items():
        c["key_figures"] = _people_for(iso)
    return countries
