"""Original study cards. Reference links are further reading, not live verification.

Keep IDs stable: progress is keyed to the first field, never to row position.
Levels: 1 foundation, 2 connections, 3 deep cuts. Hooks are learning cues.
"""
from functools import lru_cache
from urllib.parse import quote

TOPICS = [
    {"id": "history", "name": "History", "symbol": "01", "description": "Empires, revolutions & turning points"},
    {"id": "geography", "name": "Geography", "symbol": "02", "description": "Places, landscapes & the world map"},
    {"id": "science", "name": "Science & nature", "symbol": "03", "description": "From the cell to the cosmos"},
    {"id": "literature", "name": "Books & authors", "symbol": "04", "description": "Novels, characters & literary worlds"},
    {"id": "art", "name": "Art & architecture", "symbol": "05", "description": "Paintings, movements & monuments"},
    {"id": "music", "name": "Music", "symbol": "06", "description": "Composers, albums & musical language"},
    {"id": "screen", "name": "Film & television", "symbol": "07", "description": "Directors, characters & British TV"},
    {"id": "sport", "name": "Sport & games", "symbol": "08", "description": "Rules, trophies & sporting history"},
    {"id": "mythology", "name": "Myth & belief", "symbol": "09", "description": "Gods, stories & sacred traditions"},
    {"id": "words", "name": "Words & language", "symbol": "10", "description": "Roots, rhetoric & curious vocabulary"},
    {"id": "food", "name": "Food & drink", "symbol": "11", "description": "Ingredients, techniques & origins"},
    {"id": "technology", "name": "Ideas & inventions", "symbol": "12", "description": "Computing, philosophy & discovery"},
]

# id | topic | level | prompt | answer | aliases (; separated) | explanation | memory cue | reference article
ROWS = """
h01|history|1|Which treaty, signed in 1919, set the peace terms between Germany and the Allied powers after World War I?|Treaty of Versailles|Versailles|It was signed at the Palace of Versailles. Other defeated Central Powers signed separate treaties.|Versailles → Germany → 1919. Do not confuse it with the 1918 armistice.|Treaty of Versailles
h02|history|1|Which English king sealed Magna Carta in 1215?|King John|John;John of England|Rebellious barons compelled John to accept the charter at Runnymede. It was a medieval political settlement, not universal suffrage.|John at Runnymede: king, place, charter.|Magna Carta
h03|history|2|Which dynasty ruled China immediately before the Qing?|Ming|Ming dynasty|The Ming ruled from 1368 to 1644. The Qing was China's last imperial dynasty.|Ming before Qing: two adjacent names on the timeline.|Ming dynasty
h04|history|2|Which Haitian revolutionary leader was captured by the French and died in France in 1803?|Toussaint Louverture|Toussaint;Louverture;Toussaint L'Ouverture|Louverture led a major phase of the Haitian Revolution. Jean-Jacques Dessalines declared independence in 1804, after Louverture's death.|Louverture leads; Dessalines declares independence.|Toussaint Louverture
h05|history|2|Which agreements of 1648 ended the Thirty Years' War?|Peace of Westphalia|Westphalia;Treaty of Westphalia|The settlements were negotiated at Münster and Osnabrück. The war had devastated much of central Europe.|Thirty Years' War: 1618 to 1648; finish in Westphalia.|Peace of Westphalia
h06|history|1|Which Japanese period began with the restoration of imperial rule in 1868?|Meiji|Meiji era;Meiji period|The Meiji Restoration ended the Tokugawa shogunate and accompanied rapid institutional and industrial change.|Meiji = Japan's nineteenth-century transformation.|Meiji Restoration
h07|history|3|Which Roman emperor issued the Edict of Caracalla in 212 CE, extending citizenship to most free inhabitants of the empire?|Caracalla||The measure is also called the Constitutio Antoniniana. It concerned free inhabitants, not the abolition of slavery.|Caracalla → citizenship → 212.|Constitutio Antoniniana
h08|history|2|Which African ruler made a famously lavish pilgrimage to Mecca in 1324?|Mansa Musa|Musa;Musa I|Musa ruled the Mali Empire. Accounts of his journey describe extraordinary distributions of gold.|Mali, Musa, Mecca: three M's.|Mansa Musa
h09|history|3|What was the name of the 1521 imperial assembly before which Martin Luther defended his writings?|Diet of Worms|Worms|A diet was an imperial assembly; Worms is a German city. The resulting edict condemned Luther.|A political diet in a city called Worms—not a meal.|Diet of Worms
h10|history|2|Which battle in 732 is associated with Charles Martel stopping an Umayyad force in Frankish territory?|Battle of Tours|Tours;Battle of Poitiers;Poitiers|The battle is called Tours or Poitiers. Charles Martel was Charlemagne's grandfather.|Martel means hammer; connect him to Tours, not Waterloo.|Battle of Tours
g01|geography|1|Which strait separates mainland Asia from North America?|Bering Strait|Bering|It lies between Russia and Alaska, linking the Chukchi Sea with the Bering Sea.|Bering bridges the mental map from Siberia to Alaska.|Bering Strait
g02|geography|1|Which river flows through Baghdad?|Tigris|Tigris River|The Tigris and Euphrates frame the historic region of Mesopotamia. Baghdad stands on the Tigris.|Baghdad → Tigris; Mesopotamia → two rivers.|Tigris
g03|geography|2|Which lake is the deepest freshwater lake on Earth?|Lake Baikal|Baikal|Baikal is in Siberia. Depth and surface area are different records: the biggest-looking lake on a map need not be deepest.|Baikal is the deep Siberian bowl.|Lake Baikal
g04|geography|2|Which country contains the ancient city of Petra?|Jordan||Petra is associated with the Nabataeans and is famous for buildings carved into sandstone cliffs.|Petra → stone → Jordan's rock-cut city.|Petra
g05|geography|2|Which sea has boundaries defined by ocean currents rather than surrounding land?|Sargasso Sea|Sargasso|It is a region of the North Atlantic named for floating Sargassum seaweed.|Sargassum gives Sargasso its name.|Sargasso Sea
g06|geography|1|What is the capital of Bhutan?|Thimphu|Thimpu|Bhutan lies in the eastern Himalayas between India and China. Thimphu is its capital.|Pair the country and capital aloud: Bhutan–Thimphu.|Thimphu
g07|geography|3|What is the name of the Russian exclave between Poland and Lithuania?|Kaliningrad Oblast|Kaliningrad|Its principal city was formerly Königsberg. It is separated from the rest of Russia by other countries.|Königsberg became Kaliningrad; find it on the Baltic.|Kaliningrad Oblast
g08|geography|2|Which desert extends along much of Namibia's Atlantic coastline?|Namib|Namib Desert|The Namib is a coastal desert. The cold Benguela Current contributes to the region's aridity and fog.|Namibia and Namib share their name; think Atlantic coast.|Namib
g09|geography|3|Which mountain range separates much of European Russia from Siberia?|Ural Mountains|Urals;Ural|The Urals form part of the conventional boundary between Europe and Asia.|The Urals are a continental dividing line, not a national border.|Ural Mountains
g10|geography|2|What is the largest island in the Mediterranean Sea by area?|Sicily||Sicily lies off the toe of Italy. Sardinia is the second largest Mediterranean island.|The island being kicked by Italy's boot is the largest.|Sicily
s01|science|1|Which organelle is the main site of aerobic ATP production in most eukaryotic cells?|Mitochondrion|Mitochondria|Mitochondria carry out oxidative phosphorylation. Plants have them too; chloroplasts serve a different role.|Mitochondria → usable cellular energy, including in plants.|Mitochondrion
s02|science|1|Which chemical element has the symbol W?|Tungsten|Wolfram|W comes from wolfram, an alternative name for tungsten.|Wolfram explains the otherwise surprising W.|Tungsten
s03|science|2|What is the boundary around a black hole beyond which light cannot escape to distant observers called?|Event horizon|Horizon|The event horizon is a boundary in spacetime. It is not a solid surface or the central singularity.|Horizon = limit of what an outside observer can see.|Event horizon
s04|science|2|Which scientist formulated the three laws of planetary motion using elliptical orbits?|Johannes Kepler|Kepler|Kepler described planetary motion; Newton later supplied a gravitational explanation.|Kepler describes the orbits; Newton explains the force.|Kepler's laws of planetary motion
s05|science|2|What is the name for the symbiotic association between a fungus and a plant's roots?|Mycorrhiza|Mycorrhizae|Many plants exchange carbon compounds with fungi that help them obtain water and mineral nutrients.|Myco = fungus; rhiza = root.|Mycorrhiza
s06|science|1|Which scale ranks minerals from talc to diamond by scratch hardness?|Mohs scale|Mohs;Mohs hardness scale|Talc is 1 and diamond is 10. The scale ranks resistance to scratching, not resistance to shattering.|Mohs measures scratches, not toughness.|Mohs scale
s07|science|3|What name describes different structural forms of the same chemical element, such as diamond and graphite?|Allotropes|Allotrope;Allotropy|Diamond and graphite consist of carbon atoms arranged differently. Isotopes instead differ in neutron number.|Allotrope = arrangement; isotope = neutron count.|Allotropy
s08|science|2|Which blood vessels carry blood away from the heart?|Arteries|Artery|Direction defines arteries. Pulmonary arteries carry oxygen-poor blood from the heart to the lungs.|Artery = away. Oxygen level is not the definition.|Artery
s09|science|3|Which moon of Saturn has a dense nitrogen-rich atmosphere and surface lakes of liquid hydrocarbons?|Titan||Titan has methane and ethane lakes. Europa, a moon of Jupiter, is associated with a subsurface water ocean.|Titan: Saturn, thick air, methane lakes.|Titan (moon)
s10|science|2|What is the SI unit of electrical resistance?|Ohm|Ohms|Resistance is measured in ohms, current in amperes, and potential difference in volts.|Ohm's law: V = IR; resistance is R.|Ohm
l01|literature|1|Who wrote the novel Things Fall Apart?|Chinua Achebe|Achebe|Achebe's novel follows Okonkwo and the disruption of Igbo life under colonialism.|Achebe → Okonkwo → Things Fall Apart.|Things Fall Apart
l02|literature|1|Who created the detective Hercule Poirot?|Agatha Christie|Christie|Poirot is Belgian. Christie's other celebrated detective, Miss Marple, is English.|Poirot: Belgian detective, British author.|Hercule Poirot
l03|literature|2|Which fictional town is the principal setting of One Hundred Years of Solitude?|Macondo||Gabriel García Márquez's novel follows generations of the Buendía family in Macondo.|Márquez → Macondo → many Buendías.|One Hundred Years of Solitude
l04|literature|2|Who wrote the play Waiting for Godot?|Samuel Beckett|Beckett|Vladimir and Estragon wait for a figure who never arrives. Beckett originally wrote the play in French.|Beckett's pair wait; Godot stays absent.|Waiting for Godot
l05|literature|2|What pen name did Mary Ann Evans use?|George Eliot|Eliot|Her novels include Middlemarch and The Mill on the Floss. Do not confuse her with poet T. S. Eliot.|George Eliot → Middlemarch; T. S. Eliot → The Waste Land.|George Eliot
l06|literature|3|Who wrote the eleventh-century Japanese work The Tale of Genji?|Murasaki Shikibu|Murasaki|A lady-in-waiting at the Heian court, Murasaki wrote a major early work of long-form prose fiction.|Murasaki → Genji → Heian Japan.|The Tale of Genji
l07|literature|1|Which novel begins with the narrator introducing himself as Ishmael?|Moby-Dick|Moby Dick|Herman Melville's novel follows Captain Ahab's obsessive pursuit of a white whale.|Ishmael narrates; Ahab pursues.|Moby-Dick
l08|literature|3|What surname is shared by the brothers Dmitri, Ivan and Alexei in a Dostoevsky novel?|Karamazov|The Brothers Karamazov|The Brothers Karamazov explores faith, morality and family conflict. Alexei is often called Alyosha.|Dmitri, Ivan, Alyosha: the Karamazov brothers.|The Brothers Karamazov
l09|literature|2|Which poet wrote Paradise Lost?|John Milton|Milton|The epic retells the fall of humanity in blank verse, with Satan, Adam and Eve among its central figures.|Milton → lost Eden → Paradise Lost.|Paradise Lost
l10|literature|2|In which novel does the scientist Victor create a living being from assembled body parts?|Frankenstein|Frankenstein or The Modern Prometheus|Mary Shelley wrote the novel. Frankenstein is the creator's surname, not the creature's given name.|Victor Frankenstein makes the unnamed creature.|Frankenstein
a01|art|1|Who painted Guernica?|Pablo Picasso|Picasso|The painting responds to the 1937 bombing of the Basque town during the Spanish Civil War.|Guernica = Picasso's anti-war painting, not a portrait.|Guernica (Picasso)
a02|art|1|Which architect designed Fallingwater in Pennsylvania?|Frank Lloyd Wright|Wright|The house incorporates a waterfall into its setting and is associated with organic architecture.|Wright builds with the landscape: a house over falling water.|Fallingwater
a03|art|2|Which artist painted The Persistence of Memory, famous for its melting watches?|Salvador Dalí|Dali;Salvador Dali|Dalí was associated with Surrealism, a movement exploring dreamlike and unexpected imagery.|Dalí → dream → drooping watches.|The Persistence of Memory
a04|art|2|Which architect designed the dome of Florence Cathedral?|Filippo Brunelleschi|Brunelleschi|His engineering solution allowed the enormous masonry dome to be built without conventional full wooden centering.|Brunelleschi crowns Florence.|Florence Cathedral
a05|art|2|What technique uses small dots of distinct colour to build a painted image?|Pointillism||Georges Seurat and Paul Signac are closely associated with this technique.|Points of colour → pointillism → Seurat.|Pointillism
a06|art|3|Which Japanese artist created The Great Wave off Kanagawa?|Katsushika Hokusai|Hokusai|The woodblock print belongs to Thirty-six Views of Mount Fuji. Fuji appears small beneath the wave.|Look past Hokusai's wave: the series is about Fuji.|The Great Wave off Kanagawa
a07|art|2|Who sculpted The Thinker?|Auguste Rodin|Rodin|The figure originated in Rodin's project The Gates of Hell, inspired by Dante.|Rodin thinks at the Gates of Hell.|The Thinker
a08|art|3|Which art school was founded by Walter Gropius in 1919?|Bauhaus|The Bauhaus|Founded in Weimar, the school combined art, craft and design and later moved to Dessau and Berlin.|Gropius → Bauhaus → design meets function.|Bauhaus
a09|art|2|Which painter is associated with the large Water Lilies series?|Claude Monet|Monet|Monet repeatedly painted the pond at his garden in Giverny. Édouard Manet was a different artist.|Monet's garden at Giverny; keep Monet and Manet separate.|Water Lilies (Monet series)
a10|art|3|What name describes the strong contrast of light and dark used to model forms in painting?|Chiaroscuro||The Italian term joins words for light and dark. It is associated with dramatic modelling of volume.|Chiaro = light; scuro = dark.|Chiaroscuro
m01|music|1|Who composed the orchestral suite The Planets?|Gustav Holst|Holst|Its seven movements refer to astrological characters, including Mars and Jupiter. Earth is not a movement.|Holst's planets are characters: Mars the bringer of war.|The Planets
m02|music|1|Which band released the album Rumours in 1977?|Fleetwood Mac||Rumours includes Dreams, Go Your Own Way and The Chain.|Rumours → Fleetwood Mac; associate three songs with the album.|Rumours (album)
m03|music|2|Who composed the opera The Magic Flute?|Wolfgang Amadeus Mozart|Mozart|The work includes spoken dialogue and the Queen of the Night's famous high soprano writing.|Mozart → Magic Flute → Queen of the Night.|The Magic Flute
m04|music|2|What musical term means to pluck a string rather than bow it?|Pizzicato||In orchestral string playing, arco instructs the player to return to bowing.|Pizzicato plucks; arco uses the bow.|Pizzicato
m05|music|2|Which jazz trumpeter led the sessions for the 1959 album Kind of Blue?|Miles Davis|Davis|The album is a landmark of modal jazz and features musicians including John Coltrane and Bill Evans.|Miles Davis → Kind of Blue → modal jazz.|Kind of Blue
m06|music|3|Who composed the ballet The Rite of Spring?|Igor Stravinsky|Stravinsky|Its 1913 Paris premiere became famous for audience uproar. The music uses striking rhythmic accents.|Stravinsky → spring → 1913 Paris.|The Rite of Spring
m07|music|2|Which British singer was born Farrokh Bulsara?|Freddie Mercury|Mercury|The Queen frontman was born in Zanzibar and spent part of his childhood in India.|Farrokh → Freddie → Queen.|Freddie Mercury
m08|music|3|What is the lowest standard male voice type in classical singing?|Bass||The usual male categories rise from bass through baritone to tenor.|Bass below baritone below tenor.|Bass (voice type)
m09|music|2|Which composer wrote the four-concerto set The Four Seasons?|Antonio Vivaldi|Vivaldi|The set consists of violin concertos, one for each season, and includes musical depictions of natural sounds.|Vivaldi's violin visits four seasons.|The Four Seasons (Vivaldi)
m10|music|3|Which composer wrote the opera Peter Grimes?|Benjamin Britten|Britten|First performed in 1945, it concerns a fisherman and the coastal community around him.|Britten → British coast → Peter Grimes.|Peter Grimes
f01|screen|1|Who directed the 1954 film Seven Samurai?|Akira Kurosawa|Kurosawa|The Japanese film inspired the American western The Magnificent Seven.|Samurai become gunslingers: Seven Samurai → Magnificent Seven.|Seven Samurai
f02|screen|1|Which animation studio made Spirited Away?|Studio Ghibli|Ghibli|Hayao Miyazaki directed the film, whose young protagonist is Chihiro.|Ghibli is the studio; Miyazaki is the director.|Spirited Away
f03|screen|2|Who directed the 1927 silent science-fiction film Metropolis?|Fritz Lang|Lang|Made in Germany, Metropolis is known for its futuristic city and robot imagery.|Lang → Metropolis → silent futuristic city.|Metropolis (1927 film)
f04|screen|2|Which British comedy series is set in a Torquay hotel run by Basil?|Fawlty Towers||John Cleese plays Basil Fawlty. He co-wrote the series with Connie Booth.|Basil Fawlty's hotel gives Fawlty Towers its name.|Fawlty Towers
f05|screen|2|What is the name of the spaceship in the original 1979 film Alien?|Nostromo|USCSS Nostromo|Ridley Scott directed the film. Ellen Ripley is played by Sigourney Weaver.|Alien: Scott directs, Weaver plays Ripley, Nostromo is the ship.|Alien (film)
f06|screen|3|Which filmmaker directed the Apu Trilogy?|Satyajit Ray|Ray|The Bengali-language trilogy begins with Pather Panchali and follows Apu from childhood into adulthood.|Ray → Apu → Pather Panchali.|The Apu Trilogy
f07|screen|2|Which actor played the First Doctor in Doctor Who when it began in 1963?|William Hartnell|Hartnell|Hartnell originated the televised role. Patrick Troughton succeeded him as the Second Doctor.|Hartnell first; Troughton second.|First Doctor
f08|screen|3|Which film features the fictional newspaper magnate Charles Foster Kane?|Citizen Kane||Orson Welles directed and starred in the 1941 film. Rosebud is the central remembered word.|Kane, Welles, Rosebud: three linked retrieval cues.|Citizen Kane
f09|screen|2|Which British children's television programme began in 1958 and is associated with a badge featuring a ship?|Blue Peter||Its title refers to a maritime signal flag. The ship motif connects the programme's name and badge.|Blue Peter → nautical flag → ship badge.|Blue Peter
f10|screen|3|Who directed the 1966 film The Battle of Algiers?|Gillo Pontecorvo|Pontecorvo|The film depicts events in the Algerian struggle against French colonial rule using a documentary-like style.|Pontecorvo → Algiers → anti-colonial struggle.|The Battle of Algiers
p01|sport|1|What score is called a birdie in golf?|One under par|1 under par;one under;1 under|-1 relative to a hole's par is a birdie; -2 is an eagle and -3 is an albatross.|Birds get bigger as the score gets lower.|Par (score)
p02|sport|1|Which chess piece moves in an L shape and can jump over intervening pieces?|Knight|The knight|A knight moves two squares along one axis and one along the other. It alternates square colour on each move.|Knight jumps; bishops stay on one colour.|Knight (chess)
p03|sport|2|What trophy is contested by England and Australia in their traditional Test cricket series?|The Ashes|Ashes|The name comes from a mock obituary for English cricket after an 1882 defeat at The Oval.|England–Australia → cricket → Ashes.|The Ashes
p04|sport|2|How many points is a try worth in rugby union?|5|five|A conversion can add two points. Rugby league has a different scoring system.|Union: five for the try, two for the kick.|Try (rugby)
p05|sport|2|In which sport is the yellow jersey worn by the overall leader of the Tour de France?|Cycling|Road cycling;Bicycle racing|The yellow jersey represents the general classification leader, based on accumulated time.|Yellow = overall time; green = points classification.|Yellow jersey
p06|sport|3|What is the maximum break in standard snooker without a free ball?|147|one hundred and forty seven;one hundred forty seven|Fifteen reds with fifteen blacks score 120, followed by the six colours worth 27.|15 × 8 + 27 = 147.|Maximum break
p07|sport|2|Which country hosted the first men's FIFA World Cup in 1930?|Uruguay||Uruguay also won that tournament, defeating Argentina in the final.|First host and first winner: Uruguay, 1930.|1930 FIFA World Cup
p08|sport|3|Which trophy is awarded to the men's singles champion at the Australian Open?|Norman Brookes Challenge Cup|Norman Brookes;Norman Brookes Cup|The women's singles trophy is the Daphne Akhurst Memorial Cup.|Australian Open: Brookes for men, Akhurst for women.|Australian Open
p09|sport|2|What is the distance of a marathon in kilometres?|42.195|42.195 km;42.195 kilometres;42.195 kilometers|The standard distance is 42 kilometres and 195 metres, approximately 26 miles 385 yards.|Keep the odd tail: 42 plus .195.|Marathon
p10|sport|3|In fencing, which weapon allows the entire body as a valid target?|Épée|Epee|Foil targets the torso; sabre targets the body above the waist, with specific exclusions.|Épée = entire body.|Épée
y01|mythology|1|Which Greek goddess is associated with wisdom and the owl?|Athena|Athene|Athena is also associated with skilled craft and strategic warfare. Minerva is her Roman counterpart.|Athena → owl → wisdom; Rome calls her Minerva.|Athena
y02|mythology|1|What is the name of Thor's hammer?|Mjölnir|Mjolnir;Mjollnir|Thor is the Norse thunder god. Odin, a different god, carries the spear Gungnir.|Thor's hammer versus Odin's spear.|Mjölnir
y03|mythology|2|Which Egyptian god of the dead is commonly depicted with a jackal's head?|Anubis||Anubis is associated with embalming and funerary rites. Osiris is another major deity of the afterlife.|Anubis → jackal → embalming.|Anubis
y04|mythology|2|Who ferries the dead across the underworld's rivers in Greek mythology?|Charon||Funerary coins are traditionally associated with paying the ferryman. Cerberus is the underworld's guard dog.|Charon rows; Cerberus guards.|Charon
y05|mythology|2|What is the name of the great world tree in Norse mythology?|Yggdrasil|Yggdrasill|The tree connects the mythological worlds. It is commonly described as an ash.|Yggdrasil ties the Norse worlds together.|Yggdrasil
y06|mythology|3|Which Mesopotamian hero is the king of Uruk in an ancient epic?|Gilgamesh||The epic follows Gilgamesh and his companion Enkidu and explores mortality.|Gilgamesh → Uruk → Enkidu → mortality.|Epic of Gilgamesh
y07|mythology|2|Which Hindu deity is recognisable by an elephant's head?|Ganesha|Ganesh|Ganesha is widely associated with beginnings and the removal of obstacles.|Elephant head → Ganesha → beginnings.|Ganesha
y08|mythology|3|Which Greek figure was condemned to roll a boulder uphill only for it to fall back again?|Sisyphus|Sisyphos|A Sisyphean task is laborious and endlessly repeated without completion.|Sisyphus pushes; the task never stays finished.|Sisyphus
y09|mythology|2|Which religion's sacred scripture is the Guru Granth Sahib?|Sikhism|Sikh|The text holds the status of the eternal Guru in Sikh tradition.|Guru Granth Sahib → Sikh scripture and Guru.|Guru Granth Sahib
y10|mythology|3|Which Greek muse is traditionally associated with history?|Clio|Kleio|The nine Muses preside over different arts and intellectual pursuits. Calliope is associated with epic poetry.|Clio chronicles; Calliope sings epics.|Clio
w01|words|1|What is a word or phrase that reads the same forwards and backwards called?|Palindrome||Level and radar are examples. Longer phrases usually ignore spaces and punctuation.|Radar travels out and back unchanged.|Palindrome
w02|words|1|Which language supplied the word karaoke to English?|Japanese||The term combines elements meaning empty and orchestra.|Karaoke = empty orchestra; the singer supplies the voice.|Karaoke
w03|words|2|What rhetorical device pairs apparently contradictory terms, as in deafening silence?|Oxymoron||An oxymoron compresses a contradiction into a phrase. A paradox is a broader apparent contradiction.|Two clashing terms in one phrase → oxymoron.|Oxymoron
w04|words|2|What does the Latin phrase carpe diem mean?|Seize the day|seize the day!|The phrase is associated with the poet Horace and an appeal to make use of the present.|Carpe grabs; diem is the day.|Carpe diem
w05|words|2|What is the study of the historical origins of words called?|Etymology||Entomology is the study of insects. The near-identical spellings make a classic quiz trap.|Etymology = words; entomology = insects.|Etymology
w06|words|3|What name is given to a manuscript whose earlier writing has been erased and overwritten?|Palimpsest||Traces of the earlier text may survive and can sometimes be recovered by imaging.|A palimpsest has layers of writing.|Palimpsest
w07|words|2|Which writing system's name comes from a Latin word meaning wedge-shaped?|Cuneiform||Wedge-like impressions were pressed into clay. The script was used for multiple ancient languages, including Sumerian and Akkadian.|Cuneiform wedges in clay; not one single language.|Cuneiform
w08|words|3|What term describes the substitution of a related name, such as the Crown for the monarchy?|Metonymy||The connection is association. Synecdoche more specifically uses a part to represent a whole or vice versa.|Metonymy: associated thing. Synecdoche: part and whole.|Metonymy
w09|words|2|Which language family includes Finnish, Estonian and Hungarian?|Uralic|Uralic languages|These languages do not belong to the Indo-European family that contains most European languages.|Finnish, Estonian, Hungarian: the Uralic trio to remember.|Uralic languages
w10|words|3|What is the dot over a lowercase i or j called?|Tittle||Tittle can also mean a very small amount or detail.|A tiny title? No: a tittle is the tiny dot.|Tittle
c01|food|1|Which spice consists of the dried stigmas of Crocus sativus flowers?|Saffron||Each flower produces only a few stigmas, contributing to the labour needed to harvest the spice.|Saffron comes from flower stigmas, not seeds.|Saffron
c02|food|1|What is the main ingredient of traditional hummus besides tahini?|Chickpeas|Chickpea;Garbanzo beans;Garbanzo bean|Tahini is sesame paste. Chickpeas supply the body of the dip.|Hummus: chickpeas plus sesame tahini.|Hummus
c03|food|2|Which French sauce is traditionally made from milk thickened with a butter-and-flour roux?|Béchamel|Bechamel;Bechamel sauce|Béchamel is a white sauce. Velouté uses light stock rather than milk.|Béchamel = milk; velouté = stock.|Béchamel sauce
c04|food|2|Which Japanese food is made by fermenting soybeans into sticky, stringy beans?|Nattō|Natto|Nattō is commonly eaten with rice. It differs from tofu, which is made by coagulating soy milk.|Nattō ferments whole beans; tofu sets soy milk.|Nattō
c05|food|2|Which Italian cheese is traditionally used in tiramisu?|Mascarpone||Mascarpone is a rich, soft cheese made from cream. Tiramisu also commonly includes coffee-soaked ladyfingers.|Tiramisu → coffee, ladyfingers, mascarpone.|Tiramisu
c06|food|3|Which chemical process produces much of the browning flavour when bread toasts and meat sears?|Maillard reaction|Maillard|The reaction involves amino compounds and reducing sugars. Caramelisation involves sugars without requiring amino compounds.|Maillard: proteins meet sugars; caramelisation: sugars alone.|Maillard reaction
c07|food|2|What is the main grain in traditional polenta?|Maize|Corn;Cornmeal;Maize meal|The familiar Italian preparation is made from ground maize cooked in liquid.|Polenta → ground corn; risotto → rice.|Polenta
c08|food|3|Which French term means cooking food sealed in a bag in a carefully controlled water bath?|Sous vide|Sous-vide|The phrase means under vacuum. Temperature control allows food to cook evenly.|Sous vide: sealed bag, controlled bath.|Sous vide
c09|food|2|Which spirit is the traditional alcoholic base of a mojito?|Rum|White rum|The drink is associated with Cuba and commonly includes lime, mint, sugar and soda water.|Mojito → mint → Cuban rum.|Mojito
c10|food|3|What is the Japanese stock commonly made from kombu and dried bonito flakes called?|Dashi||Dashi is a foundation of many Japanese soups and dishes. Variants use other ingredients, including mushrooms.|Dashi is the stock; miso is the fermented paste.|Dashi
t01|technology|1|Who is credited with inventing the World Wide Web while working at CERN?|Tim Berners-Lee|Berners-Lee;Tim Berners Lee|The Web uses linked documents and HTTP. It is a service built on the Internet, not a synonym for the entire Internet.|Berners-Lee → Web; the Internet is the underlying network.|Tim Berners-Lee
t02|technology|1|What does CPU stand for?|Central processing unit||The CPU executes program instructions. Memory and storage have different roles.|Processing, not permanent storage.|Central processing unit
t03|technology|2|Who wrote notes on the Analytical Engine that included an algorithm for Bernoulli numbers?|Ada Lovelace|Lovelace|She worked on an account of Charles Babbage's proposed machine. Her notes discussed possibilities beyond numerical calculation.|Babbage designs the engine; Lovelace writes the notes.|Ada Lovelace
t04|technology|2|Which philosopher is associated with the statement I think, therefore I am?|René Descartes|Descartes;Rene Descartes|The formulation is often given in Latin as cogito, ergo sum. It connects the act of doubting to the existence of a thinker.|Cogito → Descartes → certainty through thought.|Cogito, ergo sum
t05|technology|2|What base does the binary numeral system use?|2|two;base 2|Binary uses the digits 0 and 1. Hexadecimal instead uses base 16.|Bi = two; binary has two digits.|Binary number
t06|technology|3|Which twentieth-century mathematician proved the incompleteness theorems?|Kurt Gödel|Godel;Gödel;Kurt Godel|The theorems concern limits of sufficiently expressive, consistent formal systems of arithmetic, not the claim that nothing can be proved.|Gödel → limits of formal proof.|Gödel's incompleteness theorems
t07|technology|2|Who developed the smallpox vaccination method using cowpox in 1796?|Edward Jenner|Jenner|Jenner's work helped establish vaccination. It was distinct from the older practice of variolation using smallpox material.|Jenner → cowpox → protection against smallpox.|Edward Jenner
t08|technology|3|Which philosopher proposed the veil of ignorance as a way to reason about justice?|John Rawls|Rawls|The thought experiment asks people to choose social principles without knowing their own future position in society.|Rawls: choose the rules before learning your place.|Veil of ignorance
t09|technology|2|What does the S in HTTPS stand for?|Secure||HTTPS uses encryption through TLS. Encryption protects the connection; it does not guarantee that a website's claims are true.|Secure connection is not the same as a trustworthy claim.|HTTPS
t10|technology|3|What is the name of the hypothetical test Alan Turing proposed in 1950 involving a machine's conversational behaviour?|Turing test|Imitation game;The imitation game|The test concerns whether a machine can be distinguished from a human through conversation, not a direct measurement of consciousness.|Turing → imitation game → conversation.|Turing test
"""


@lru_cache(maxsize=1)
def cards():
    result = []
    for row in ROWS.strip().splitlines():
        key, topic, level, prompt, answer, aliases, explanation, hook, article = row.split("|")
        result.append({"id": key, "topic": topic, "level": int(level), "prompt": prompt,
                       "answer": answer, "aliases": aliases.split(";") if aliases else [],
                       "explanation": explanation, "hook": hook,
                       "source": "https://en.wikipedia.org/wiki/" + quote(article.replace(" ", "_")),
                       "source_label": "Read more: " + article})
    return result
